application: 
  # accept connections from any network interface
  # significantly increase teh "audience" with some security implications
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "something@gmail.com"
